### ISSUE TITLE
The code works perfect with sqlite but does not work with mysql

### ISSUE THREAD

**Issue by ajithcse** [miguelgrinberg/oreilly-intro-to-flask-video#6]
I tried to use mysql instead of sqlite

I changed the following code

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///data.sqlite3'
to

app.config['SQLALCHEMY_DATABASE_URI'] ='mysql://userid:pass@localhost/db_name'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
users table is created in db_name DB with data given in the code.

But when tried to login using the credentials login does not work.

I'm not sure where I have gone wrong.

FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = LoginForm()

**Comment by miguelgrinberg** [comment]
> But when tried to login using the credentials login does not work.

Is this a database login or an application login?

**Comment by ajithcse** [comment]
I dint understand your question, 

but when i run python  login.py users table is created in Mysql db. username john and hashed value of cat are stored in table.

Application opens fine in the browser. but after entering john as username and cat as password and when submitted, page redirects to login again.

**Comment by miguelgrinberg** [comment]
Sorry I wasn't clear. I was wondering if you had issues logging in to the database or to the application. You have answered anyway, it's clearly the latter.

What you need to do is add a print statement right before you validate the password in the server. Print the username and the password, so that we know if the credentials are arriving at the server intact or are getting corrupted.

Also, I assume you have tested running `user.verify_password('cat')` in a Python console to make sure the password hash is correct in the database?

**Comment by ajithcse** [comment]
when tried user.verify_password('cat') error as below
![image](https://user-images.githubusercontent.com/52650350/62102469-b9a68200-b2b6-11e9-817f-3166d45866ee.png)

**Comment by ajithcse** [comment]
database screenshot

![image](https://user-images.githubusercontent.com/52650350/62102533-fd998700-b2b6-11e9-8a0e-f2608cae5621.png)

**Comment by miguelgrinberg** [comment]
On the terminal screenshot, you haven't loaded your `user` variable. See how I do this in the tutorial. You also haven't done the printing that I requested.

Please reopen if you want to continue troubleshooting this issue.
